services:
  # Infrastructure Services
  redis:
    image: redis:7-alpine
    container_name: factory-redis
    # Remove external port exposure for security
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - database-network

  influxdb:
    image: influxdb:2.7
    container_name: factory-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXD_HTTP_CORS_ENABLED=true
      - INFLUXD_HTTP_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://127.0.0.1:3000
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - database-network
      - backend-network

  # Application Services
  plc-emulator:
    build:
      context: ./services
      dockerfile: plc-emulator/Dockerfile
    container_name: factory-plc-emulator
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - UPDATE_INTERVAL=2000
      - HEARTBEAT_INTERVAL=30000
      - CONFIG_DIRECTORY=/app/infrastructure/config
    volumes:
      - ./infrastructure/config:/app/infrastructure/config
      - plc_logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - backend-network
      - database-network

  queue-consumer:
    build:
      context: ./services
      dockerfile: queue-consumer/Dockerfile
    container_name: factory-queue-consumer
    depends_on:
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - CONSUMER_CONCURRENCY=5
      - ENABLE_HEALTH_ENDPOINT=true
      - HEALTH_PORT=8080
      - CONFIG_DIRECTORY=/app/infrastructure/config
      - LOG_TRANSFORMATIONS=true
    volumes:
      - ./infrastructure/config:/app/infrastructure/config
      - consumer_logs:/app/logs
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - backend-network
      - database-network

  # Authentication Service
  auth-service:
    build:
      context: ./services
      dockerfile: auth-service/Dockerfile
    container_name: factory-auth-service
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTH_SERVICE_PORT=3005
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3002
    ports:
      - "3005:3005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - frontend-network
      - database-network

  # Dashboard Application
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - VITE_INFLUXDB_URL=http://localhost:8086
        - VITE_INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
        - VITE_INFLUXDB_ORG=${INFLUXDB_ORG}
        - VITE_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
        - VITE_DEPLOYMENT_ENV=docker
        - VITE_DATA_SOURCE=influxdb
    container_name: factory-dashboard
    depends_on:
      - influxdb
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - frontend-network

  # Reverse Proxy with SSL
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: factory-nginx
    depends_on:
      - dashboard
      - auth-service
      - grafana
      - queue-consumer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - frontend-network
      - backend-network
      - monitoring-network

  # Monitoring and Management
  grafana:
    image: grafana/grafana:latest
    container_name: factory-grafana
    depends_on:
      - influxdb
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - monitoring-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: factory-redis-commander
    depends_on:
      - redis
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - database-network

volumes:
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  grafana_data:
    driver: local
  plc_logs:
    driver: local
  consumer_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  database-network:
    driver: bridge
  monitoring-network:
    driver: bridge